version: 2

sources:
  - name: datasources
    tables:
    - name: entitegestion_2008_2023
      identifier: entitegestion_2008_2023
      freshness:
        warn_after: {count: 1, period: day}
        error_after: {count: 7, period: day}