version: 2

sources:
  - name: datasources
    tables:
    - name: entite_gestion
      identifier: entite_gestion
      freshness:
        warn_after: {count: 1, period: day}
        error_after: {count: 7, period: day}
    - name: composition_communale
      identifier: composition_communale
      freshness:
        warn_after: {count: 1, period: day}
        error_after: {count: 7, period: day}
    - name: cities
      identifier: cities
      freshness:
        warn_after: {count: 1, period: day}
        error_after: {count: 7, period: day}